infile=open('file1.txt','r')
content=infile.read()
infile.close()
outfile=open('file2.txt','w')
outfile.write(content)
words=content.split(' ')
length=len(words)
print('The total length of word is',length)
print('The word count of each word is ---')
noDuplicate=list(set(words))
print('{0:15} {1:5}'.format('word','count'))
fp=open('file3.txt','w')
fp.write('{0:15} | {1:5}\n'.format('word','wordcount'))
fp.write('--------------------------------------\n')
for word in noDuplicate:
 fp.write('{0:15}|{1:5}\n'.format(word,word.count(word)))
fp.close()
outfile.close()
